<?php

//Public path
define('PATH_PUBLIC','public/');

// Image Path
define('PATH_IMAGE','public/image/');

// staff image Path
define('PATH_STAFF_IMAGE','staff_image/');

// member image Path
define('PATH_MEMBER_IMAGE','member_image/');

// class image Path
define('PATH_CLASS_IMAGE','class_image/');


// temp staff image path
define('SYSTEM_TEMP_DIRECTORY','temp/');

// unauthorized access
define("UNAUTHORIZED_ACCESS","Unauthorized access detected.");
// session timeout
define("SESSION_TIMED_OUT","Session timed out.");

//Business name
define("SYSTEM_BUSINESS_NAME", 'Hiru Fitness Center');

//Live host url CMS
define("LIVE_HOST_URL_CMS","mygym.test:8888/cms/");

//Live host url web
define("LIVE_HOST_URL_WEB","mygym.test:8888/");

//Email footer
define("EMAIL_FOOTER", "Mail Generated By Hiru Fitness Center");

//System Email
define("SYSTEM_EMAIL", 'peramuna49@hotmail.com');

//Email Host
define("EMAIL_HOST", 'smtp.live.com');

//App key
define("APP_KEY", 'lbp@hotmail');

//Unknown error
define("UNKNOWN_ERROR", "Unknown Error");
?>