<?php

//Public path
define('PATH_PUBLIC','public/');

// Image Path
define('PATH_IMAGE','public/image/');

// staff image Path
define('PATH_STAFF_IMAGE','staff_image/');

// member image Path
define('PATH_MEMBER_IMAGE','member_image/');

// class image Path
define('PATH_CLASS_IMAGE','class_image/');

// event image Path
define('PATH_EVENT_IMAGE','event_image/');

// equipment image Path
define('PATH_EQUIPMENT_IMAGE','equipment_image/');

// package image Path
define('PATH_PACKAGE_IMAGE','package_image/');



// temp image path
define('SYSTEM_TEMP_DIRECTORY','temp/');

// unauthorized access
define("UNAUTHORIZED_ACCESS","Unauthorized access detected.");
// session timeout
define("SESSION_TIMED_OUT","Session timed out.");

//Business name
define("SYSTEM_BUSINESS_NAME", 'LBP Fitness Center');

//Live host url CMS
define("LIVE_HOST_URL_CMS","mygym.test:8888/cms/");

//Live host url web
define("LIVE_HOST_URL_WEB","mygym.test:8888/");

//Email footer
define("EMAIL_FOOTER", "Mail Generated By LBP Fitness Center");

//System Email
define('SYSTEM_EMAIL', 'lbpfitness@co.uk');

//System Email
define('EMAIL_USERNAME', 'd37836aa1053be');

//Email Host
define('EMAIL_HOST', 'smtp.mailtrap.io');

//App key
define('EMAIL_KEY', 'fec66187f85f28');

//Unknown error
define("UNKNOWN_ERROR", "Unknown Error");

// PayPal Environment 
define("PAYPAL_ENVIRONMENT", "sandbox");

// PayPal REST API endpoints
define("PAYPAL_ENDPOINTS", array(
	"sandbox" => "https://api.sandbox.paypal.com",
	"production" => "https://api.paypal.com"
));

// PayPal REST App credentials
define("PAYPAL_CREDENTIALS", array(
	"sandbox" => [
		"client_id" => "AYlQfl6viyLGGvrWWMy-Eh-EuCL7zif-5QNg_qFoaUwgMagmPqtTFaOc4gD7C9riW6kQWKyrgQ5IPHol",
		"client_secret" => "EPh-y5JHipYO9IBwFnSuLFZ3cXReZnJAjjCg0e2ikH_DOkXXHlCbj7g4DPNfrspeBvRnYUSrM5EWQjLV"
	],
	"production" => [
		"client_id" => "",
		"client_secret" => ""
	]
));

// Business email
define('BUSINESS_EMAIL','pglbuddhika@gmail.com');

// Business phone
define('BUSINESS_PHONE','+94771888110');

//openexchangerates app id
define('OPENEXCHANGERATES_APP_ID', '35c38025e1ef434786933b036608a6e4');

//address line 1
define('ADDRESS_LINE_1', 'No');

//address line 2
define('ADDRESS_LINE_2', 'Line 1');

//admin area 2
define('ADMIN_AREA_2', 'Line 2');

//admin area 1
define('ADMIN_AREA_1', 'State');

//postal code 
define('POSTAL_CODE', '****');

//country
define('COUNTRY', 'LK');

//country
define('COUNTRY_CODE', '094');

//country
define('NATIONAL_NUMBER', '771888110');

//paypal account email
define('PAYPAL_EMAIL', 'pglbuddhika-facilitator@gmail.com');

//website 
define('WEB_SITE', 'www.lbpfitness.co.uk');


